version: '3'
services:
    markov-tweet:
        restart: always
        container_name: markov-tweet
        image: ghcr.io/yuderobot/markov-tweet:master
        build: .
        volumes:
          - "./data:/app/data"
        environment:
          # Twitter API related
          - CK=
          - CS=
          - AT=
          - AS=
          # Length of sentence
          - N=1